services:
  db:
    image: mysql:8.0
    container_name: "mysql_8.0"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wp_manager_site
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uadmin", "-padmin"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s
    networks:
      wp_network:
        ipv4_address: 193.18.0.3

  wordpress:
    container_name: "wordpress"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WP_VERSION: ${WP_VERSION:-latest}
    image: wp-plugin-boilerplate/wordpress:latest
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./.env:/var/www/html/.env
    environment:
      WORDPRESS_DB_NAME: wp_manager_site
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_HOST: 193.18.0.3
      WORDPRESS_DB_CHARSET: utf8
      WORDPRESS_DB_COLLATE: ""
      WORDPRESS_CONFIG_EXTRA: |
        define( 'FS_METHOD', 'direct' );
    env_file: .env
    ports:
      - "8000:80"
    restart: always
    networks:
      wp_network:
        ipv4_address: 193.18.0.2

volumes:
  db_data: {}

networks:
  wp_network:
    ipam:
      driver: default
      config:
        - subnet: 193.18.0.0/16
